SELECT * FROM T_PROFESSOR;

SELECT COUNT(*), COUNT(HPAGE) FROM T_PROFESSOR;	-- 그룹함수에서는 NULL 값은 계산에서 제외

SELECT COUNT(*), COUNT(BONUS), SUM(BONUS), AVG(BONUS) FROM T_PROFESSOR;

SELECT MAX(HIREDATE) FROM T_EMP;

-- NULL 허용 컬럼의 그룹함수 적용시
-- NVL, NVL2 사용해야 함.
SELECT AVG(BONUS), AVG(NVL(BONUS, 0))
FROM T_PROFESSOR;

-- T_PROFESSOR 테이블에서 '학과별'로 교수님들의 평균 보너스를 출력하세요.
SELECT DEPTNO, AVG(BONUS) 
FROM T_PROFESSOR;

SELECT DEPTNO, ROUND(AVG(NVL(BONUS, 0)),1) "보너스 평균" 
FROM T_PROFESSOR
GROUP BY DEPTNO
;

-- #5101
SELECT DEPTNO, "POSITION", AVG(PAY) "평균 급여" 
FROM T_PROFESSOR
GROUP BY DEPTNO, "POSITION"	-- 1. 학과별 그룹핑, 2. 직급별 그룹핑
ORDER BY DEPTNO ASC, "POSITION" ASC
;

-- 부서별 평균굽여를 출력하되, 평균급여가 450보다 많은 학과만 출력
SELECT DEPTNO, AVG(PAY) "평균급여" 
FROM T_PROFESSOR 
WHERE AVG(PAY) > 450	-- 그룹함수는 WHERE 절에서 사용불가!!!
GROUP BY DEPTNO 
;
-- HAVING : 그룹함수 결과에 대한 조건절
SELECT DEPTNO, AVG(PAY) "평균급여" 
FROM T_PROFESSOR 
GROUP BY DEPTNO 
HAVING AVG(PAY) > 300

-- #5102
--SELECT *
SELECT MGR, COUNT(*), SUM(SAL), AVG(SAL), AVG(NVL(COMM ,0)) 
FROM T_EMP
WHERE JOB <> 'PRESIDENT'
GROUP BY MGR
--ORDER BY MGR DESC
;

-- #5103
--SELECT *
SELECT DEPTNO, COUNT(*) AS "총인원", ROUND(AVG(SYSDATE - HIREDATE), 1) AS "근속평균", AVG(PAY) AS "급여평균", AVG(NVL(BONUS, 0)) AS "보너스 평균"
FROM T_PROFESSOR 
WHERE "POSITION" IN ('정교수', '조교수')
GROUP BY DEPTNO 
;

-- #5104
SELECT DEPTNO1 AS "학과", MAX(WEIGHT)-MIN(WEIGHT) AS "최대최소 몸무게차"
FROM T_STUDENT 
GROUP BY DEPTNO1
;

-- #5105
SELECT DEPTNO1 AS "학과", MAX(WEIGHT)-MIN(WEIGHT) AS "최대최소 몸무게차"
FROM T_STUDENT 
GROUP BY DEPTNO1
--HAVING "최대최소 몸무게차" >= 30
HAVING MAX(WEIGHT)-MIN(WEIGHT) >= 30
;