
DROP TABLE T_STUDENT CASCADE CONSTRAINTS;
DROP TABLE T_PROFESSOR CASCADE CONSTRAINTS;
DROP TABLE T_DEPARTMENT CASCADE CONSTRAINTS;


CREATE TABLE T_DEPARTMENT
(
	DEPTNO number NOT NULL,
	DNAME varchar2(30) NOT NULL,
	PRIMARY KEY (DEPTNO)
);


CREATE TABLE T_PROFESSOR
(
	PROFNO number NOT NULL,
	NAME varchar2(30) NOT NULL,
	ID varchar2(30) NOT NULL,
	PAY number NOT NULL,
	DEPTNO number NOT NULL,
	PRIMARY KEY (PROFNO)
);


CREATE TABLE T_STUDENT
(
	STUDNO number NOT NULL,
	NAME varchar2(30) NOT NULL,
	ID varchar2(30) NOT NULL,
	GRADE number,
	DEPTNO number NOT NULL,
	PROFNO number NOT NULL,
	PRIMARY KEY (STUDNO)
);

ALTER TABLE T_PROFESSOR
	ADD FOREIGN KEY (DEPTNO)
	REFERENCES T_DEPARTMENT (DEPTNO)
;


ALTER TABLE T_STUDENT
	ADD FOREIGN KEY (DEPTNO)
	REFERENCES T_DEPARTMENT (DEPTNO)
;


ALTER TABLE T_STUDENT
	ADD FOREIGN KEY (PROFNO)
	REFERENCES T_PROFESSOR (PROFNO)
;



