
/* Drop Triggers */

DROP TRIGGER TRI_STUDENT_STDNUM;



/* Drop Tables */

DROP TABLE TAKE CASCADE CONSTRAINTS;
DROP TABLE LECTURE CASCADE CONSTRAINTS;
DROP TABLE PROFESSOR CASCADE CONSTRAINTS;
DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_STUDENT_STDNUM;




/* Create Sequences */

CREATE SEQUENCE SEQ_STUDENT_STDNUM INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE DEPARTMENT
(
	DEPNO number NOT NULL UNIQUE,
	TELL varchar2(15) UNIQUE,
	OFFICE varchar2(30),
	DEPNAME varchar2(30),
	PRIMARY KEY (DEPNO)
);


CREATE TABLE LECTURE
(
	LECNO number NOT NULL UNIQUE,
	NAME varchar2(30),
	CREDIT varchar2(3),
	TRAINNUM number,
	CLASSROOM varchar2(10),
	YEARS date,
	PROFNO number NOT NULL UNIQUE,
	PRIMARY KEY (LECNO)
);


CREATE TABLE PROFESSOR
(
	PROFNO number NOT NULL UNIQUE,
	JUMIN char(13),
	ADRESS varchar2(50),
	NAME varchar2(15),
	POSITION varchar2(15),
	PHONE varchar2(15),
	HIERED date,
	DEPNO number NOT NULL UNIQUE,
	PRIMARY KEY (PROFNO)
);


CREATE TABLE STUDENT
(
	STDNUM number NOT NULL UNIQUE,
	NAME varchar2(30) NOT NULL,
	GRADE number,
	JUMIN char(13) NOT NULL,
	PHONE varchar2(13) UNIQUE,
	ADRESS varchar2(30),
	DEPNO number NOT NULL UNIQUE,
	PRIMARY KEY (STDNUM)
);


CREATE TABLE TAKE
(
	STDNUM number NOT NULL UNIQUE,
	LECNO number NOT NULL UNIQUE
);



/* Create Foreign Keys */

ALTER TABLE PROFESSOR
	ADD FOREIGN KEY (DEPNO)
	REFERENCES DEPARTMENT (DEPNO)
;


ALTER TABLE STUDENT
	ADD FOREIGN KEY (DEPNO)
	REFERENCES DEPARTMENT (DEPNO)
;


ALTER TABLE TAKE
	ADD FOREIGN KEY (LECNO)
	REFERENCES LECTURE (LECNO)
;


ALTER TABLE LECTURE
	ADD FOREIGN KEY (PROFNO)
	REFERENCES PROFESSOR (PROFNO)
;


ALTER TABLE TAKE
	ADD FOREIGN KEY (STDNUM)
	REFERENCES STUDENT (STDNUM)
;



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_STUDENT_STDNUM BEFORE INSERT ON STUDENT
FOR EACH ROW
BEGIN
	SELECT SEQ_STUDENT_STDNUM.nextval
	INTO :new.STDNUM
	FROM dual;
END;

/




