INSERT INTO TEST_MEMBER VALUES(10, '남윤주', sysdate);
SELECT * FROM TEST_MEMBER ;

INSERT INTO TEST_MEMBER VALUES (22, '이승환', '1994-02-21');
INSERT INTO TEST_MEMBER VALUES (17, '윤종섭', '2019-08-03');
INSERT INTO TEST_MEMBER VALUES ('', '이예지', '');
INSERT INTO TEST_MEMBER VALUES (NULL, '늦음', '');
