-- FROM 절에 테이블에도 별칭(alias)를 줄수 있다.
-- 20레코드
SELECT S.STUDNO ,S.NAME ,S.DEPTNO1 
FROM T_STUDENT S
;
-- 12레코드
SELECT D.DEPTNO ,D.DNAME 
FROM T_DEPARTMENT D
;

SELECT *
FROM T_STUDENT ;
SELECT *
FROM T_DEPARTMENT ;

-- 카티션곱 (Cartesian Product)
-- 두개의 테이블을 JOIN 하게 되면, 
-- 각 테이블의 레코드들의 모든 조합이 출력된다.
-- WHERE 나 ON 등으로 JOIN 조건이 주어지지 않으면 
-- 모든 카티션곱이 출력된다. 
SELECT *
FROM T_STUDENT S, T_DEPARTMENT D
;
SELECT S.STUDNO ,S.NAME ,S.DEPTNO1 ,D.DEPTNO ,D.DNAME 
FROM T_STUDENT S, T_DEPARTMENT D
;

SELECT S.STUDNO ,S.NAME ,S.DEPTNO1 ,D.DEPTNO ,D.DNAME
FROM T_STUDENT S CROSS JOIN T_DEPARTMENT D	-- ANSI 방식
;

-- Equi JOIN (등가 JOIN)
-- ORACLE 방식
SELECT S.NAME "학생이름", S.DEPTNO1 "학과번호", D.DNAME "학과이름"
FROM T_STUDENT S,T_DEPARTMENT D
WHERE S.DEPTNO1 = D.DEPTNO	-- EQUI JOIN (조건으로 검색)
;

-- ANSI 방식
SELECT S.NAME "학생이름", S.DEPTNO1 "학과번호", D.DNAME "학과이름"
FROM T_STUDENT S JOIN T_DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO -- EQUI JOIN (조건으로 검색)
;

SELECT * FROM T_STUDENT;

-- 제2전공은?
SELECT S.NAME "학생이름", S.DEPTNO2 "제2학과 이름", D.DNAME "제2학과 이름"
FROM T_STUDENT S, T_DEPARTMENT D
WHERE S.DEPTNO2 = D.DEPTNO
;

-- #6102
SELECT S.NAME "학생 이름", S.PROFNO "지도교수", P.NAME "지도교수 이름"
FROM T_STUDENT S, T_PROFESSOR P
WHERE S.PROFNO = P.PROFNO 
;

SELECT S.NAME "학생 이름", S.PROFNO "지도교수", P.NAME "지도교수 이름"
FROM T_STUDENT S JOIN T_PROFESSOR P ON S.PROFNO = P.PROFNO
;

-- #6103
-- ORACLE 방식
SELECT S.NAME "학생 이름", D.DNAME "학과명" , P.NAME "교수 이름"
FROM T_STUDENT S, T_DEPARTMENT D, T_PROFESSOR P
WHERE S.DEPTNO1 = D.DEPTNO AND S.PROFNO = P.PROFNO 
;
-- ANSI 방식
SELECT S.NAME "학생 이름", D.DNAME "학과명", P.NAME "교수 이름"
FROM T_STUDENT S
	JOIN T_DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO 
	JOIN T_PROFESSOR P ON S.PROFNO = P.PROFNO 
;

-- #6104
-- ORACLE 방식
SELECT E2.NAME "사원 이름", E2.POST "현재", E2.PAY "현재 연봉", P.S_PAY "하한금액", P.E_PAY "상한금액"
FROM T_EMP2 E2, T_POST P
WHERE E2.POST = P.POST 
;
-- ANSI 방식
SELECT E2.NAME "사원 이름", E2.POST "현재", E2.PAY "현재 연봉", P.S_PAY "하한금액", P.E_PAY "상한금액" 
FROM T_EMP2 E2
		JOIN T_POST P ON E2.POST = P.POST 
;

-- #6105
-- ORACLE
SELECT S.NAME , P.NAME 
FROM T_STUDENT S, T_PROFESSOR P
WHERE S.DEPTNO1 = 101 AND S.PROFNO = P.PROFNO 
;
-- ANSI
SELECT S.NAME , P.NAME
FROM T_STUDENT S
		JOIN T_PROFESSOR P ON S.PROFNO = P.PROFNO 
WHERE S.DEPTNO1 = 101
;
SELECT S.NAME , P.NAME
FROM T_STUDENT S
		JOIN T_PROFESSOR P ON S.PROFNO = P.PROFNO AND S.DEPTNO1 = 101
;