SELECT * FROM T_CUSTOMER ;
SELECT * FROM T_GIFT ;
-- ORACLE
SELECT C.C_NAME "고객명", C.C_POINT "포인트", G.G_NAME "상품"
FROM T_CUSTOMER C, T_GIFT G
WHERE C.C_POINT BETWEEN G.G_START AND G.G_END 
;
-- ANSI
SELECT C.C_NAME "고객명", C.C_POINT "포인트", G.G_NAME "상품"
FROM T_CUSTOMER C JOIN T_GIFT G
	ON C.C_POINT BETWEEN G.G_START AND G.G_END 
;
-- #6202
-- ORACLE
SELECT G.G_NAME "상품명", COUNT(G.G_NAME) "필요수량" 
FROM T_CUSTOMER C, T_GIFT G
WHERE C.C_POINT BETWEEN G.G_START AND G.G_END 
GROUP BY G.G_NAME
;
-- ANSI
SELECT G.G_NAME "상품명", COUNT(G.G_NAME) "필요수량" 
FROM T_CUSTOMER C JOIN T_GIFT G
	ON C.C_POINT BETWEEN G.G_START AND G.G_END 
GROUP BY G.G_NAME
;

-- #6203
-- ORACLE
SELECT S.NAME "학생이름", E1.TOTAL "점수", C.GRADE "학점" 
FROM T_STUDENT S, T_EXAM01 E1, T_CREDIT C
WHERE S.STUDNO = E1.STUDNO 
	AND E1.TOTAL BETWEEN C.MIN_POINT AND C.MAX_POINT 
;
-- ANSI
SELECT S.NAME "학생이름", E1.TOTAL "점수", C.GRADE "학점"
FROM T_STUDENT S
	JOIN T_EXAM01 E1 ON S.STUDNO = E1.STUDNO 
	JOIN T_CREDIT C ON E1.TOTAL BETWEEN C.MIN_POINT AND C.MAX_POINT 
;

-- #6204
SELECT *
FROM T_CUSTOMER 
;
SELECT *
FROM T_GIFT 
;
-- ORACLE
SELECT C.C_NAME "고객명", C.C_POINT "포인트", G.G_NAME "상품명"
FROM T_CUSTOMER C, T_GIFT G
WHERE G.G_END <= C.C_POINT
AND G.G_NAME = '산악용자전거'
;
-- ANSI
SELECT C.C_NAME "고객명", C.C_POINT "포인트", G.G_NAME "상품명"
FROM T_CUSTOMER C
		JOIN T_GIFT G ON C.C_POINT >= G.G_END AND G.G_NAME = '산악용자전거'
;

-- #6205
SELECT * FROM T_EMP2 ;
SELECT * FROM T_POST ;
-- ORACLE
SELECT E2.NAME "이름", 
		(TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(E2.BIRTHDAY, 'YYYY') + 1) "현재 나이",
		NVL(E2.POST, ' ') "현재 직급",
		P.POST "예상 직급"
FROM T_EMP2 E2, T_POST P
WHERE (TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(E2.BIRTHDAY, 'YYYY') + 1) BETWEEN P.S_AGE AND P.E_AGE
;
-- ANSI
SELECT E2.NAME "이름", 
		(TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(E2.BIRTHDAY, 'YYYY') + 1) "현재 나이",
		NVL(E2.POST, ' ') "현재 직급",
		P.POST "예상 직급"
FROM T_EMP2 E2 JOIN T_POST P ON (TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(E2.BIRTHDAY, 'YYYY') + 1) BETWEEN P.S_AGE AND P.E_AGE
;

SELECT S.NAME "학생 이름", P.NAME "교수 이름"
FROM T_STUDENT S
	LEFT OUTER JOIN T_PROFESSOR P ON S.PROFNO = P.PROFNO 
;

SELECT S.NAME "학생 이름", P.NAME "교수 이름"
FROM T_STUDENT S
	RIGHT OUTER JOIN T_PROFESSOR P ON S.PROFNO = P.PROFNO 
;

SELECT S.NAME "학생 이름", P.NAME "교수 이름"
FROM T_STUDENT S
	FULL OUTER JOIN T_PROFESSOR P ON S.PROFNO = P.PROFNO 
;

SELECT D1.DNAME "부서명", D2.DNAME "상위 부서명"
FROM T_DEPT2 D1 , T_DEPT2 D2
WHERE D1.PDEPT = D2.DCODE 
;
-- #6210
SELECT * FROM T_PROFESSOR;
SELECT P1.PROFNO "교수 번호", P1.NAME "교수명", P1.HIREDATE "입사일", COUNT(P2.NAME) "빠른 사람"
FROM T_PROFESSOR P1
	LEFT OUTER JOIN T_PROFESSOR P2 ON P1.HIREDATE > P2.HIREDATE
GROUP BY P1.PROFNO,P1.NAME,P1.HIREDATE 
ORDER BY 4
;